### ISSUE TITLE
create_config_file ILSM detection broken by multi version of same module

### ISSUE THREAD

**Issue by mohawk2** [ingydotnet/inline-pm#72]
If one has a per-arch ILSM (e.g. Inline::Pdlapp as installed as part of PDLA::Core, which has a per-arch element), and also a non-arch one (e.g. Inline::Pdlapp also installed from its own independent distro), then the logic in `create_config_file` breaks.

It does `next LIB if ($checked{$mod}++);`, which gets a false positive if it has already seen the `$mod`. That means it skips the whole `LIB`, instead of just that file. It just needs a `FILE` label, and to do `next FILE` instead.

**Comment by mohawk2** [comment]
This causes failures like:

- http://www.cpantesters.org/cpan/report/484896a4-683b-11e9-b254-3c1f1f24ea8f
- http://www.cpantesters.org/cpan/report/5ce9dfdc-67e6-11e9-8a22-0e4dcf16732d

This is definitely why, because the test first tries to load `Inline::C`, and does `skip_all` if that fails.

**Comment by perlpunk** [comment]
Fixed by #73

**Comment by mohawk2** [comment]
@perlpunk Fantastic! What's the plan for releasing? I'm still getting deluged by failures for PDLA::Core caused by this :-)
